kind: Service
apiVersion: v1
metadata:
  name: spring-app-service
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  labels:
    app: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: train-schedule
        image: sbabburu/spring-mvc-sample-image:0.1
        ports:
        - containerPort: 8080
